# Generated by Django 3.1.2 on 2020-11-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20201110_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='last_name',
        ),
    ]
