# Generated by Django 3.1.2 on 2020-11-09 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
                ('aro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recorridos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometros_total', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('valor_total', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.bicicleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
